/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CdsButton {
        "icon": string;
        "iconPosition": 'leading' | 'trailing';
        "isFullWidth": boolean;
        "size": 'large' | 'default' | 'small' | 'x-small';
        "text": string;
        "variant": 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'destructive';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCdsButtonElement extends Components.CdsButton, HTMLStencilElement {
    }
    var HTMLCdsButtonElement: {
        prototype: HTMLCdsButtonElement;
        new (): HTMLCdsButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cds-button": HTMLCdsButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CdsButton {
        "icon"?: string;
        "iconPosition"?: 'leading' | 'trailing';
        "isFullWidth"?: boolean;
        "size"?: 'large' | 'default' | 'small' | 'x-small';
        "text"?: string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'destructive';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cds-button": CdsButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cds-button": LocalJSX.CdsButton & JSXBase.HTMLAttributes<HTMLCdsButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
