/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CdsBadge {
        "size": string;
        "text": string;
        "type": string;
        "variant": string;
        "withIcon": boolean;
        "withText": boolean;
    }
    interface CdsButton {
        "customClass": string;
        "size": string;
        "text": string;
        "variant": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCdsBadgeElement extends Components.CdsBadge, HTMLStencilElement {
    }
    var HTMLCdsBadgeElement: {
        prototype: HTMLCdsBadgeElement;
        new (): HTMLCdsBadgeElement;
    };
    interface HTMLCdsButtonElement extends Components.CdsButton, HTMLStencilElement {
    }
    var HTMLCdsButtonElement: {
        prototype: HTMLCdsButtonElement;
        new (): HTMLCdsButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "cds-badge": HTMLCdsBadgeElement;
        "cds-button": HTMLCdsButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CdsBadge {
        "size"?: string;
        "text": string;
        "type"?: string;
        "variant"?: string;
        "withIcon"?: boolean;
        "withText"?: boolean;
    }
    interface CdsButton {
        "customClass"?: string;
        "size"?: string;
        "text": string;
        "variant"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "cds-badge": CdsBadge;
        "cds-button": CdsButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cds-badge": LocalJSX.CdsBadge & JSXBase.HTMLAttributes<HTMLCdsBadgeElement>;
            "cds-button": LocalJSX.CdsButton & JSXBase.HTMLAttributes<HTMLCdsButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
