import type { Meta, StoryObj } from "@storybook/react";
import Example from "./example";
declare const meta: Meta<typeof Example>;
export default meta;
type Story = StoryObj<typeof Example>;
export declare const Neutral: Story;
export declare const Info: Story;
export declare const Success: Story;
export declare const Highlight: Story;
export declare const Warning: Story;
export declare const Error: Story;
