import React from 'react'
import { describe, it, expect } from 'vitest'
import { render } from '@testing-library/react'
import { Check, X } from '../index'

/**
 * The first tests in this package, added with the safe-by-default change.
 *
 * Every icon used to render as `role="img"` unconditionally. With no `title` — the
 * overwhelmingly common case, because these icons are decorative — `titleId` is
 * `undefined`, React omits `aria-labelledby`, and the result is a `role="img"` with no
 * accessible name. Axe reports `svg-img-alt`, and when such an icon is the only child of a
 * button, that button is nameless too and axe adds `button-name`.
 *
 * That single root cause produced six shipped defects across four PRs during the Radix 0.3
 * test backfill, each fixed at the call site. This suite pins the fix at the source, so the
 * next icon-only control cannot reintroduce it.
 *
 * Icons are generated by SVGR from `.svgrrc.json`, so these assertions are really about
 * that config's `svgProps`. Two arbitrary icons are enough — every component in
 * `src/components/` is emitted from the same template.
 */

const svgIn = (container: HTMLElement) =>
	container.querySelector('svg') as SVGSVGElement

describe('icon accessibility defaults', () => {
	it('hides an untitled icon from the accessibility tree', () => {
		const { container } = render(<Check />)
		const svg = svgIn(container)

		expect(svg.getAttribute('aria-hidden')).toBe('true')
		expect(svg.hasAttribute('role')).toBe(false)
		// An `aria-hidden` element cannot trip `svg-img-alt`, which is the point.
		expect(svg.hasAttribute('aria-labelledby')).toBe(false)
	})

	it('names a titled icon and keeps it in the accessibility tree', () => {
		const { container } = render(<Check title="Saved" titleId="saved-icon" />)
		const svg = svgIn(container)

		expect(svg.getAttribute('role')).toBe('img')
		expect(svg.hasAttribute('aria-hidden')).toBe(false)
		expect(svg.getAttribute('aria-labelledby')).toBe('saved-icon')
		expect(svg.querySelector('title')?.textContent).toBe('Saved')
		expect(svg.querySelector('title')?.id).toBe('saved-icon')
	})

	it('keeps an aria-label from the caller meaningful', () => {
		// Naming an icon without rendering a <title> is the other legitimate way to make it
		// meaningful, and it must not be silently hidden by the decorative default.
		const { container } = render(<X aria-label="Close" />)
		const svg = svgIn(container)

		expect(svg.getAttribute('role')).toBe('img')
		expect(svg.hasAttribute('aria-hidden')).toBe(false)
		expect(svg.getAttribute('aria-label')).toBe('Close')
	})

	it('keeps an aria-labelledby from the caller meaningful', () => {
		const { container } = render(
			<>
				<span id="close-label">Close</span>
				<X aria-labelledby="close-label" />
			</>
		)
		const svg = svgIn(container)

		expect(svg.getAttribute('role')).toBe('img')
		expect(svg.hasAttribute('aria-hidden')).toBe(false)
		expect(svg.getAttribute('aria-labelledby')).toBe('close-label')
	})

	it('lets an explicit aria-hidden from the caller win', () => {
		// `{...props}` is spread after the computed defaults, so the caller always has the
		// last word — including un-hiding a titled icon.
		const { container } = render(<Check aria-hidden={false} />)
		expect(svgIn(container).getAttribute('aria-hidden')).toBe('false')

		const titled = render(<Check title="Saved" aria-hidden />).container
		expect(svgIn(titled).getAttribute('aria-hidden')).toBe('true')
	})

	it('lets an explicit role from the caller win', () => {
		const { container } = render(<Check role="presentation" />)
		expect(svgIn(container).getAttribute('role')).toBe('presentation')
	})
})
