name: CI - www

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '18.x'

concurrency:
   group: ci-website-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  # lint:
  #   name: "Lint"
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 7
  #     - name: Install Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ env.NODE_VERSION }}
  #         cache: 'pnpm'
  #     - name: Install Dependencies
  #       run: pnpm install
  #     - name: Lint
  #       run: pnpm run lint
  #       working-directory: apps/www
  cypress-run:
    name: "Cypress tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm start
